### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by kvngdrey123** [kamiras/BTC_address_changer#1]
Hello how do i contact you personally to remake a fud undetected one for me ,for educational purpose only.

**Comment by kamiras** [comment]
Hello! I converted the .py to .exe and it's detected by 7 of 67 antiviruses, so you wouldn't have too many problems with antiviruses. Link to the result:

https://www.virustotal.com/gui/file/5a93adfd099fd347a57e487c8f1b9aa661ff6ee3e99dc6b1e98360ec9afc7cbd/detection

The main problem that I see is that it displays the CMD every time it's executed, but that could be fixed renaming the **btcaddress.py** file to **btcaddress.pyw**. The .pyw extension will prevent the console window from opening.

**Comment by kvngdrey123** [comment]
Is there anyway I can personally contact you for business on telegram

**Comment by kamiras** [comment]
Hi there! I'm only here to enjoy developing free source code. I'm not interested in business but thank you for your interest.
